log:
  level: debug
  disable_sentry: true
  path: /var/log/link-shortener/log.txt

db:
  url: postgres://RofaBR:bo57v97dm@db:5432/link_shortener?sslmode=disable

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: link-shortener-svc
  service_port: 80
