version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://RofaBR:bo57v97dm@db:5432/link_shortener?sslmode=disable
    depends_on:
      - db
      - nginx

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: RofaBR
      POSTGRES_PASSWORD: bo57v97dm
      POSTGRES_DB: link_shortener
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db_data:
