version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8000"
    environment:
      - CONFIG_PATH=/config.yaml
    volumes:
      - ./config.yaml:/config.yaml
    depends_on:
      - db
      - nginx

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: RofaBR
      POSTGRES_PASSWORD: bo57v97dm
      POSTGRES_DB: link_shortener
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/nginx.conf

volumes:
  db_data:
